### ISSUE TITLE
Server crashes on ninjago world

### ISSUE THREAD

**Issue by BeeatZz** [DarkflameUniverse/DarkflameServer#292]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Hey! basically im stuck on ninjago world because every time i try to do the finding camps and destroying ladders for building jumpads quest i get kicked from the server and the server shuts down. Ive seen some people post an issue of this in AG but the issue was closed and i couldnt fix it, so im creating a new one 
![image](https://user-images.githubusercontent.com/96536218/147112259-192e43ba-956b-4d3d-aa06-54291dc3b756.png)
all the other crashlogs are the same. 

### Reproduction steps

Fly to ninjago and progress up until the earth ninja quest, when you reach the step where you need to help soldiers thats where it crashes

### Expected Behavior

i expected the server not to crash

### Environment

Ubuntu on virtualbox

**Comment by enteryournamehere** [comment]
The older closed issue about AG crashes was about a different problem, but this crash does also occur in Avant Gardens and Crux Prime. It should be fixed by #294

**Comment by BeeatZz** [comment]
> The older closed issue about AG crashes was about a different problem, but this crash does also occur in Avant Gardens and Crux Prime. It should be fixed by #294

can you tell me how to apply the commit? i know nothing about computers ;-;

**Comment by metric-ambient** [comment]
Also having these same error crashes when on Ninjago since updating to current build last night.

**Comment by BeeatZz** [comment]
> The older closed issue about AG crashes was about a different problem, but this crash does also occur in Avant Gardens and Crux Prime. It should be fixed by #294

Just edited the Loot.cpp file, didnt fix the issue 

![image](https://user-images.githubusercontent.com/96536218/147151235-148242ed-fb90-4f10-845d-a86cc0730768.png)

this is the last message i got and it crashed on the exact same spot as before, building the launchpads from ladders in ninjago

**Comment by BeeatZz** [comment]
Update! i tried using /completemission 2855 to complete the ladder mission and server crashed. I tried using complete mission before and it worked perfectly. got the same error as my last comment when using complete mission

**Comment by MickVermeulen** [comment]
Odd, suspecting this might be an issue in either an attached script or the mission component. Has anyone else been able to reproduce this?

**Comment by averysumner** [comment]
Has this issue persisted?

**Comment by EmosewaMC** [comment]
Does this issue still persist? Please try rebuilding a server from scratch to start from a fresh known state and ensure you are using an unpacked client to setup the server for the easiest setup.

**Comment by EmosewaMC** [comment]
Closing due to stale issue.  Please re-open if issues persist.
