### ISSUE TITLE
Need help - Can't join the server anymore 

### ISSUE THREAD

**Issue by JuuiTwitch** [DarkflameUniverse/DarkflameServer#337]
Hello,

I wanted to go to another world using the /testmap command, but It seems like I mistyped the zone id and now I'm stuck (I know, not my best idea). Every time I try to log in to the server it says "Your game assets don't match the server". Is there any way to change the position of my character to a world that exists so I can join my server again? Any help is appreciated.

**Comment by EmosewaMC** [comment]
I was able to fix this issue by changing my character XML data in a database viewer.  I changed the value for `lwid` to a safe world to get out of the loop.  A safe world would be 1100, Avant Gardens.  so changing that to `lwid=1100` should fix the issue.
![image](https://user-images.githubusercontent.com/39972741/147869813-c7e3de2f-a65e-453a-8bf0-0921b30a8316.png)

**Comment by JuuiTwitch** [comment]
> 

Thanks for your answer! Could you please explain to me in more detail how I have to do this, so what I have to change exactly?

**Comment by EmosewaMC** [comment]
Open the database in the mySQL workbench 8.0 CE

Run the following query
SELECT `charxml`.`id`,
    `charxml`.`xml_data`
FROM `dlu`.`charxml`;

there will be many characters and ids here, you will need to find with one with the lwid that is getting you stuck (see previous comment, 2nd line far right hand side.)

Navigate to the [Form Editor](https://user-images.githubusercontent.com/39972741/147896716-cf4ca7ab-eee2-4393-9f40-902e52cbb0a5.png)

Select everything from the Xml_data column and put it into a text editor (If the character you are updating is NOT the first character on your account then you can just edit the value in the workbench and apply the change.  The first character's XML data is too large to be edited in the workbench.)

find `lwid` and replace the following number with 1100(make sure to only replace the number)

open ubuntu and login to the mysql server (`mysql -u <username> -p` then `use dlu;`) and update the row to the new data (UPDATE \`dlu\`.\`charxml\` SET \`xml_data\` = \`<PASTE XML DATA HERE>\` WHERE (\`id\` = \`<id of char to update>\`);

It is important you keep all of the graves that are in the update command.  
Here is an example of me changing my characters zone from [1800 (right hand side 2nd row is where lwid is)](https://user-images.githubusercontent.com/39972741/147896991-d45c6490-8f16-400d-969f-42c4bdd204d5.png) to 
[1100](https://user-images.githubusercontent.com/39972741/147897038-d0405641-304a-452d-8398-e1808f872dac.png)

and here is the command I would type into [mysql](https://pastebin.com/PTvaMS8r)

**Comment by JuuiTwitch** [comment]
Thanks so much for your efforts! Unfortunately, I still do not understand how to do that and I will therefore delete the character and create a new one.
